# Generated by Django 2.0.3 on 2021-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=16, null=True, verbose_name='place')),
                ('longitude', models.CharField(max_length=32, verbose_name='lon')),
                ('latitude', models.CharField(max_length=32, verbose_name='lan')),
                ('time', models.DateField(auto_now_add=True, verbose_name='updatetime')),
                ('Infected', models.CharField(blank=True, max_length=32, null=True, verbose_name='infected')),
            ],
            options={
                'verbose_name': 'riskPoint',
                'verbose_name_plural': 'riskPoint',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=16, null=True, verbose_name='place')),
                ('longitude', models.CharField(max_length=32, verbose_name='lon')),
                ('latitude', models.CharField(max_length=32, verbose_name='lan')),
                ('time', models.DateField(auto_now_add=True, verbose_name='updatetime')),
                ('Infected', models.CharField(blank=True, max_length=32, null=True, verbose_name='infected')),
            ],
            options={
                'verbose_name': 'risk',
                'verbose_name_plural': 'risk',
            },
        ),
    ]
